/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Starting Calculator App..");
    

    StandardCalculator calc = new StandardCalculator();

    LogicCalculator calcr = new LogicCalculator();

    calcr.OR(8, 6);

    calcr.printResult();

    calcr.AND(8, 6);

    calcr.printResult();
    
        // calc.add(10, 15);
        // calc.printResult(); 

        // calc.subtract(20, 15);
        // calc.printResult();

        // calc.multiply(20, 15);
        // calc.printResult(); 

        // calc.divide(20, 15);
        // calc.printResult(); 

        // calc.clearResult();
        // calc.printResult();

        // calc.add1(Double.MAX_VALUE, Double.MAX_VALUE);
  
        try {
            calc.add(10.0, 5.0);
            calc.printResult();

            calc.subtract(20.0, 7.0);
            calc.printResult();

            calc.multiply(3.0, 4.0);
            calc.printResult();

            calc.divide(15.0, 3.0);
            calc.printResult();

            calc.divide(10.0, 0.0);
            calc.printResult(); 

            calc.sin(Math.PI / 6);
            calc.cos(Math.PI / 3);
            calc.square(4.0);
            calc.tan(Math.PI / 4);
            calc.log(10.0);
            calc.sqrt(25.0);
            calc.cbrt(27.0);
            
        } catch (ArithmeticException e) {
            System.out.println("Exception type: " + e.getClass().getName());
            System.out.println("Exception: " + e.getMessage());
        }
    
        calc.printResult();

}
}
